### ISSUE TITLE
Monoids 

### ISSUE THREAD

**Issue by slifin** [i-am-tom/php-folding-talk#1]
Hi

Just seen your talk on PHPSW's Youtube channel thank you for taking the time to do it

Do you mind making more examples to explain monoids in PHP? I think I'm struggling to understand the monoid, do I have to create one for each operation? I notice the logic for things like sum exist both in fold.php in an function but also in the associated monoid

What would happen if you didn't have the factory to generate the monoid what advantage would you lose?

Does the contramap loop over the data twice? once for map, then again for reduce?...  So many questions, I currently understand map/filter/reduce/partial application if that helps you understand where my questions come from

If I use this approach can I avoid looping over a collection multiple times like I currently would with map/reduce?

**Comment by i-am-tom** [comment]
Hello - glad you enjoyed the talk! I'll try to be coherent, but let me know if anything's still in a mess:

> Do you mind making more examples to explain monoids in PHP? I think I'm struggling to understand the monoid, do I have to create one for each operation? I notice the logic for things like sum exist both in fold.php in an function but also in the associated monoid

Monoids are defined by a set (we're programmers, so we can think of this as a type `X` (e.g. float, int, bool, or some fancy class we've made ourselves), an append function `f` (that takes two `X` values and returns an `X`), and a value of type `X` called the identity (`e`) for which, given any `x` of type `X`, `f(x, e) == x == f(e, x)`. That stuff's kinda complicated, but we'll think of some examples:
- the `int` type, the `+` operator, and identity `0`
- the `int` type, the `*` operator, and identity `1`
- the `string` type, the `.` operator, and identity `''`
- the `bool` type, the `||` operator, and identity `false`
- the `bool` type, the `&&` operator, and identity `true`
- the sequential `array` type, the `array_merge` function, and identity `[]` - this is actually called the _free_ monoid (because you can wrap any value in an array and do monoid stuff using this trio), but that's not important.

With any of these, if you take a value of the type, and apply it to the operator with the identity, you get back that same value. As long as that's true (and associativity holds, but don't worry too much about this right now), that trio forms a monoid.

SO.

The sum logic in the Fold class is literally just the addition operation on two numbers, just as `2 + 3` isn't a monoid sum. What makes it a monoid operation is the sum operation, the `0` identity, and the `float` (or `int`) type. The sum operation in the Fold class is just for adding numbers - it doesn't need to know about the types or the identities because they're not necessary for standard addition - whereas the `Sum` monoid needs to have these details to be a complete monoid. The important thing here is that **a monoid is an operation, a set, _and_ an identity**. You could write your monoids as three-element lists if you wanted, but classes seemed more PHP-friendly.

> What would happen if you didn't have the factory to generate the monoid what advantage would you lose?

In the answer to @Danack in the first question at the end of the talk, the factories let you add type checks, but also a weak form of type "inference". The `Pair` monoid, for example, is just a left and a right monoid. So, its identity is the pair of the left identity and the right identity, which means it needs to know what those monoids _are_ to find their identities. Factories were how I got round this in an "OO" way - your `Pair` factory is instantiated with the factories for the left and right monoids, so the identity can be calculated.

> Does the contramap loop over the data twice? once for map, then again for reduce?... So many questions, I currently understand map/filter/reduce/partial application if that helps you understand where my questions come from

Think of the Fold class as having three parts: `I -> M -> O`, which is some **i**nput to some **m**onoid to some **o**utput. When we map over the fold, we do it with a function `O -> P` - we take the value of the output, and transform it to a new value, which gives us a new Fold that we could write as `I -> M -> P`.

Contramap is exactly the same but we _pre_process the `I` value. So, we could contramap with some function `J -> I`, and we'd get a new fold `J -> M -> P`. All it does is return a new Fold with your given function glued to the start (just as map returns a new Fold with your given function glued to the end). So, it still only does one pass over the list - it just does some extra logic before and after.

If you're curious about this pre- and post-processing, `Fold` is actually what we'd call a _profunctor_ - a structure with two parts (input and output) that you can contramap and map respectively. It's pretty intense if you're relatively new to functional programming, though, so I wouldn't worry too much about this.

> If I use this approach can I avoid looping over a collection multiple times like I currently would with map/reduce?

This is probably the purest implementation of map/reduce, really. We're transforming the values (map), folding them up (reduce), and getting an end result. However, if you tend to do multiple map/reduce operations on the same data and then combine the results afterwards, this will _definitely_ optimise that for larger data sets. All it's doing, under the complexity, is keeping track of the intermediate values. It just looks kinda ugly in PHP, hah!

---

I hope that explains things... if not, please reply with another load of questions! I want this stuff to be as accessible as possible, so I'm quite happy to go over all this again :)

**Comment by slifin** [comment]
Is there a functional way of implementing those factories for monoids that are hard to have an identity function for? 

Is it possible for example to have identity() on pair that returns a function that when resolved returns the type? once the parameters have been fully resolved? (left|right) presumably

**Comment by slifin** [comment]
Also in the comments to http://www.haskellforall.com/2013/08/composable-streaming-folds.html
which you've referenced in your source code the author says a different approach "produces strikingly more efficient code" as supplied by one of the commenters: 

http://squing.blogspot.co.uk/2008/11/beautiful-folding.html

Is the second approach (seems like it uses folds but not monoids) useful to us in PHP land? I can't really judge because I do not understand haskell's syntax

**Comment by i-am-tom** [comment]
Sorry for the delay - been all over the place!

**In answer to the first post:**

It depends on what you mean by "functional". If you mean pure/stateless/referentially transparent, then there's nothing wrong with the way used in this library. If you mean closer to "Haskell-like", then the type system isn't good enough for PHP to do this. In Haskell-like languages, you define the Pair monoid, in part, by the types of its left and right monoids. Then, when you call `mempty` (the identity value), it is resolved to whichever value is correct for those monoids at compile-time.

PHP can't do this level of type specification, so you have to do it at run-time, and that's exactly what the factory does - looks at its run-time-given type (i.e. the factories passed into the constructor), and build an identity that matches. It that sense, it's as functional as you can get in the language that we're given... not pretty, but this way at least looks more comfortable in OO, I think...

**In answer to the second:**

The concept of a `fold`, as you rightly pointed out, doesn't require monoids - for arrays (lists), it's literally just a function for combining list elements, and a starting value. What this method does is, instead of explicitly keeping track of intermediate values via a pair structure, it composes a bigger reduction function. This is basically the same except for two things: you don't set the identity within the fold structure (you pass it in separately, just like with `array_reduce`), and you don't _enforce_ things like associativity (which you do (at least implicitly) by using `Monoid` in Haskell). 

The first allows a bit more flexibility - you don't have to start with an identity! - but means you have to carry an extra parameter around. The second makes no difference until you want to rewrite the code in this repo to deal with multiple threads - whereas saying something is a monoid means you're declaring its operation as associative (because that's a law of monoids), the same isn't true for any folding function, so you can't guarantee that it can be parallelised in a mechanical way.

In practice, the first doesn't really matter for PHP, because we'd write a structure to hold them both (for convenience) and that would pretty much be a monoid anyway. The reason your example benches faster for Haskell is that you're getting rid of the intermediate structure and it's a language specifically designed for lightweight functions. I suspect that PHP is quite the opposite - designed for structures (objects) over lots of anonymous functions. So, porting it to PHP probably wouldn't make any difference worth mentioning, simply due to the nature of PHP.

That said, it'd be a good intermediate exercise - write `array_reduce` as a class that constructs with a function `$folder` to use, and has a `fold($init, $values)` method that returns `array_reduce($values, $folder, $init)`. Then, you implement `both`/`bothWith`/`after` by returning _new_ instances that wrap the `$folder` function in corresponding functions to modify its behaviour.

---

I hope that makes sense - I'm typing all this in a hurry, so, again, leave a comment if any of this is rushed or meaningless! :)
